// Generated by gencpp from file msgpkg/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MSGPKG_MESSAGE_ADDTWOINTS_H
#define MSGPKG_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <msgpkg/AddTwoIntsRequest.h>
#include <msgpkg/AddTwoIntsResponse.h>


namespace msgpkg
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace msgpkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::msgpkg::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::msgpkg::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::msgpkg::AddTwoInts > {
  static const char* value()
  {
    return "msgpkg/AddTwoInts";
  }

  static const char* value(const ::msgpkg::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::msgpkg::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::msgpkg::AddTwoInts >
template<>
struct MD5Sum< ::msgpkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::msgpkg::AddTwoInts >::value();
  }
  static const char* value(const ::msgpkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgpkg::AddTwoIntsRequest> should match
// service_traits::DataType< ::msgpkg::AddTwoInts >
template<>
struct DataType< ::msgpkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::msgpkg::AddTwoInts >::value();
  }
  static const char* value(const ::msgpkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::msgpkg::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::msgpkg::AddTwoInts >
template<>
struct MD5Sum< ::msgpkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::msgpkg::AddTwoInts >::value();
  }
  static const char* value(const ::msgpkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgpkg::AddTwoIntsResponse> should match
// service_traits::DataType< ::msgpkg::AddTwoInts >
template<>
struct DataType< ::msgpkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::msgpkg::AddTwoInts >::value();
  }
  static const char* value(const ::msgpkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSGPKG_MESSAGE_ADDTWOINTS_H
